### PR TITLE
Fix/thousand separator

### LINKED ISSUE #1435: Thousand Separator
### Directorist version

v7.6

### Environment

_No response_

### Description

https://tasks.hubstaff.com/app/organizations/37274/projects/338303/tasks/5477632
https://tasks.hubstaff.com/app/organizations/37274/projects/265387/tasks/4787672

### Steps to reproduce

In checkout page

### Isolating the problem

- [X] I have reproduced this bug in localhost.
- [X] This bug happens with a default WordPress theme active (eg. 2021, 2022 etc).

### PR DESCRIPTION
**Pull request by vairafiq**
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Security fix
- [x] Improvement
- [ ] New Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

## Description
How to reproduce the issue or how to test the changes

## Any linked issues
Fixes #1435 

## Checklist

- [ ] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

### CODE REVIEW

File: includes/payments/functions.php [hunk 1]
```diff
@@ -100,42 +100,8 @@ function atbdp_get_payment_bulk_actions()
...
-    if( $decimals ) {
-        $decimals  = atbdp_currency_decimal_count( 2, $currency );
-    } else {
-        $decimals = 0;
-    }
-
-    $formatted = number_format( (float)$amount, $decimals, $decimal_sep, $thousands_sep );
-
-    return apply_filters( 'atbdp_format_amount', $formatted, $amount, $decimals, $decimal_sep, $thousands_sep );
+    return apply_filters( 'atbdp_format_amount', number_format_i18n( (int) $amount, 2 ), $amount, $decimals, $currency_settings );
```
Comment (obiPlabon) [inline includes/payments/functions.php:104]: The changes don't consider the 'allow_decimal' settings. It should.

File: includes/payments/class-order.php [hunk 2]
```diff
@@ -340,7 +340,7 @@ public function manage_order_columns($column, $post_id)
                 $currency        = atbdp_get_payment_currency();
                 $symbol          = atbdp_currency_symbol($currency);
                 ('after' == $c_position) ? $after = $symbol : $before = $symbol;
-                echo esc_attr( $before . atbdp_format_payment_amount( $value ) . $after );
+                echo esc_attr( $before . $value . $after );
```
Comment (obiPlabon) [inline includes/payments/class-order.php:343]: `esc_html` should be used here.

**Review by obiPlabon — CHANGES_REQUESTED** [review]

**Review by obiPlabon — APPROVED** [review]
Looks good
